import UserSessionModel from "./session";
import UserModel from "./user";
import MediaModel from "./media";
import IndustriesModel from "./industries";
import CityModel from "./city";
import JobModel from "./jobs";
import SmtpSettingModel from "./smtp";
import ManageContentModel from "./manageContent";
import ManageKeyModel from "./manageKey";
import EmployerModel from "./employer";
import JobDocumentModel from "./jobDocument";
import CompanyImageModel from "./companyImage";
import ApplicationModel from "./jobApplication";
import AppoinmentModel from "./appoinment";
import JobImagesModel from "./jobImages";
import JobTypesModel from "./jobType";
import EmployeeModel from "./employee";
import EmployeeSessionModel from "./employee.session";

export const userSessionModel = UserSessionModel;
export const userModel = UserModel;
export const mediaModel = MediaModel;
export const industriesModel = IndustriesModel;
export const cityModel = CityModel;
export const jobModel = JobModel;
export const smtpSettingModel = SmtpSettingModel;
export const manageContentModel = ManageContentModel;
export const manageKeyModel = ManageKeyModel;
export const employerModel = EmployerModel;
export const jobDocumentModel = JobDocumentModel;
export const companyImageModel = CompanyImageModel;
export const applicationModel = ApplicationModel;
export const appoinmentModel = AppoinmentModel;
export const jobImagesModel = JobImagesModel;
export const jobTypesModel = JobTypesModel;
export const employeeModel = EmployeeModel;
export const employeeSessionModel = EmployeeSessionModel;
